# Generated by Django 3.2.3 on 2021-06-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0002_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='batman.png', upload_to='fotoPerfil'),
        ),
    ]
