# Generated by Django 3.2.3 on 2021-06-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='escom.png', upload_to='fotoPerfil'),
        ),
    ]
