# Generated by Django 3.2.3 on 2021-06-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0006_auto_20210608_2128'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', 'post'], name='appWeb_like_user_id_0481d1_idx'),
        ),
    ]
